# Generated by Django 2.0.4 on 2018-04-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='node',
            order_with_respect_to='parent',
        ),
    ]
