# Generated by Django 2.0.4 on 2018-04-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='numbering',
            field=models.BooleanField(default=True),
        ),
    ]
